env:
  browser: true
  commonjs: true
  es6: true
  jest: true
extends:
  - airbnb-base
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules:
  semi: [2, 'never']
  func-names: ['error', 'never']
  consistent-return: 'off'
  no-restricted-syntax: 0
  indent: ['error', 'tab']
  no-tabs: ['error', { allowIndentationTabs: true }]
  no-plusplus: ['off', { allowForLoopAfterthoughts: true }]
  no-unused-vars: ['error']

#####################
# Jest plugin seems uneccessary with env:jest:true applied
# https://www.npmjs.com/package/eslint-plugin-jest
